### ISSUE TITLE
[Bug] MoneyBatch

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/samples-java#143] opened 2021-08-17 02:58 UTC
### Describe the bug

The count and balance should be cleared after this line:

https://github.com/temporalio/samples-java/blame/master/src/main/java/io/temporal/samples/moneybatch/AccountTransferWorkflowImpl.java#L51

### To Reproduce

Run two batches in succession and notice that the second batch is never deposited.

**Comment by tsurdilo** [comment] 2021-08-17 13:33
@joebowbeer thanks for the info - looking into it.

**Comment by tsurdilo** [comment] 2021-08-24 03:05
@joebowbeer after looking into this I don't think that this is an issue. 
batch size is set to 3 meaning that you need to run TransferRequester 3 times before the wait condition in the workflow:

          Workflow.await(() -> count == batchSize);

is satisfied. Each time you run the TransferRequester the workflows withdraw signal method is called and it updates the balance and the count, when the count is 3, then the balance is deposited.

Hope this helps. I will close this issue as it's not a bug in my opinion. Feel free to reopen it if you still think otherwise with info why. 
Thank you again for raising this issue!

**Closed** 2021-08-24 03:06 UTC
Labels: bug

**Comment by tsurdilo** [comment] 2021-08-24 03:09
@joebowbeer I understand that the code:

          BatchRequest request = workflowClient.newSignalWithStartRequest();
          request.add(transferWorkflow::deposit, to, BATCH_SIZE);
          request.add(transferWorkflow::withdraw, from, reference, amountCents);
           workflowClient.signalWithStart(request);

might be confusing. It would be the same as you started the workflow and then called its withdraw signal method.

**Comment by joebowbeer** [comment] 2021-08-24 04:46
@tsurdilo I agree. Thanks for your diligence. If I had run the sample I would have seen that it functions correctly:

```
Activity Worker started for task queue: Account
Withdraw to account1 of 100 cents requested
Withdraw to account1 of 100 cents requested
Withdraw to account1 of 125 cents requested
Deposit to account2 of 325 cents requested
Withdraw to account1 of 25 cents requested
Withdraw to account1 of 125 cents requested
Withdraw to account1 of 25 cents requested
Deposit to account2 of 175 cents requested
```
